### PR TITLE
added endpoint to get all students with pagination

### PR DESCRIPTION
**Pull request by piotr07**

### CODE REVIEW

**Review by RafalG1991 — COMMENTED** [review]
Works fine but it require to pass the page number to the path, otherwise it throws a 500 server error.
Maybe just make it optional and as a default pass the first page to the method when we fetch to /student without page number?

```
@Get('/:pageNumber?')
  findAll(
    @Param('pageNumber') pageNumber?: string,
  ): Promise<GetPaginatedListOfUser> {
    return this.studentService.findAll(pageNumber ? Number(pageNumber) : 1);
  }
```

**Comment by piotr07** [comment]
> Works fine but it require to pass the page number to the path, otherwise it throws a 500 server error. Maybe just make it optional and as a default pass the first page to the method when we fetch to /student without page number?
> 
> ```
> @Get('/:pageNumber?')
>   findAll(
>     @Param('pageNumber') pageNumber?: string,
>   ): Promise<GetPaginatedListOfUser> {
>     return this.studentService.findAll(pageNumber ? Number(pageNumber) : 1);
>   }
> ```

I've set parametr "pageNumber" as optional and I changed returned data in JSON.

**Review by RafalG1991 — APPROVED** [review]
Now it works perfectly fine - with or without passing the page number

**Comment by piotr07** [comment]
Added second parametr for pass items per page :)

**Comment by RafalG1991** [comment]
Resolved conflicts and tested new feature - items per page parameter works as intended with or without the page number param

**Pull request merged**
